from datetime import datetime
from typing import cast

from psycopg import Connection
from psycopg.rows import dict_row
from psycopg_pool import ConnectionPool

from core.utils.env import DATABASE_URL

try:
    UserDict = dict[str, str | datetime]
    DirectoryDict = dict[str, int | str | datetime | None]
    FileDict = dict[str, int | str | datetime | list[str] | None]
    GitHubCursorDict = dict[str, int]

    POOL: ConnectionPool[Connection[dict[str, int | str | datetime | list[str] | None]]] = cast(
        ConnectionPool[Connection[dict[str, int | str | datetime | list[str] | None]]], cast(object, ConnectionPool(
            DATABASE_URL,
            kwargs={"row_factory": dict_row},
        )))

    with POOL.connection() as connection:
        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS users (
                username   TEXT PRIMARY KEY,
                password   TEXT        NOT NULL,
                first_name TEXT        NOT NULL,
                last_name  TEXT        NOT NULL,
                created_at TIMESTAMPTZ NOT NULL
            );

            CREATE TABLE IF NOT EXISTS directories (
                id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                path        TEXT        NOT NULL,
                modified_at TIMESTAMPTZ NOT NULL,
                deleted_at  TIMESTAMPTZ,
                username    TEXT        NOT NULL,

                CONSTRAINT fk_directories_user
                    FOREIGN KEY (username)
                        REFERENCES users (username),

                CONSTRAINT unique_directory_path
                    UNIQUE (path, username)
            );

            CREATE TABLE IF NOT EXISTS files (
                id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                directory_id BIGINT      NOT NULL,
                name         TEXT        NOT NULL,
                type         TEXT        NOT NULL,
                size         BIGINT      NOT NULL,
                modified_at  TIMESTAMPTZ NOT NULL,
                data_center  TEXT        NOT NULL,
                links        TEXT []     NOT NULL,
                deleted_at   TIMESTAMPTZ,
                username     TEXT        NOT NULL,

                CONSTRAINT fk_files_directory
                    FOREIGN KEY (directory_id)
                        REFERENCES directories (id),

                CONSTRAINT fk_files_user
                    FOREIGN KEY (username)
                        REFERENCES users (username)
            );

            CREATE TABLE IF NOT EXISTS github_cursor (
                repo_id BIGINT PRIMARY KEY,
                used    BIGINT NOT NULL
            );
            """
        )
        connection.commit()

except Exception as e:
    print(f"Failed to connect: {e}")
